version: "3.8"

services:
  # Sourced from https://github.com/localstack/localstack/blob/master/docker-compose.yml
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    hostname: localstack
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - HOSTNAME_EXTERNAL=localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  dynamodbadmin:
    container_name: "dynamodb-admin"
    image: "aaronshaf/dynamodb-admin"
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://localstack:4566"
      AWS_REGION: "us-east-1"
    depends_on:
      - localstack